name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: ${{ github.ayushtripathi-45 }}

      - name: Push output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
